### PR TITLE
[BUGFIX] Generate frontend url within backend compatible with all current TYPO3 version back to v7

### LINKED ISSUE #21: Throws Exception when creating TSFEController in TYPO3 10 with enablePurgeByUrl
Everytime I try to clear the cache for a single page or through `clearCacheCmd` in PageTSConfig I get the following Exception

```
#1561583127 InvalidArgumentException

TypoScriptFrontendController must be constructed with a valid SiteLanguage object or a resolved site in the current request as fallback. None given.
```

As it seems the constructor of `TypoScriptFrontendController` has significant changes to prior versions of TYPO3.

https://github.com/TYPO3/typo3/blob/fe16eeb92d49edc5e79041dd949bc68cf66dfdce/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php#L690-L732

Therefore the current implementation of https://github.com/xperseguers/t3ext-cloudflare/blob/8153cddbd8b8563022f3c961ace5f8ba86667220/Classes/Hooks/TCEmain.php#L178-L183 seems to need a major refactor.

At the moment I have no spontaneous idea on how to create the necessary parameters with valid options to create a working TSFE within the backend context. And it seems to be a problem multiple people have, because the search for this exception message brought plenty results. All with the base problem trying to create the TSFE in backend context. But haven't found a solution among those results yet.

### PR DESCRIPTION
**Pull request by tpinne**
This change is based on the usage of `nng/nnhelpers` package which provides various helper methods and fixes #21.

I tested it with TYPO3 v10.4.17 but the implementation suggests that it is compatible from v7 to v11 https://bitbucket.org/99grad/nnhelpers/src/a21c9811d7b47651b8b08d0247fb176ecb087524/Classes/Utilities/Tsfe.php#lines-93

### CODE REVIEW

**Comment by tpinne** [comment]
Maybe use the code of that extension as inspiration. I just noticed that it also introduces a domain model along with a new database table, which would be likely too much technical debt, for the purpose of the cloudflare extension. I'll go with it for now, because we need a quick solution to get our project onto TYPO3 v10.

**Review by xperseguers — CHANGES_REQUESTED** [review]
I'm not willing to add a dependency to nng/nnhelpers

**Comment by tpinne** [comment]
I don't say you should, but maybe use it as an inspiration for a custom implementation. 
The linked `init` method in that repo is completely based on vanilla TYPO3 classes/methods. And the version checks in that `init` method are also based on vanilla code https://bitbucket.org/99grad/nnhelpers/src/a21c9811d7b47651b8b08d0247fb176ecb087524/Classes/nnhelpers.php#lines-354

```php
public static function t3Version() {
	return floor(VersionNumberUtility::convertVersionNumberToInteger(TYPO3_version)/1000000);
}
```

Currently I don't know how much more there is to do to generate absolute url in regards to support all TYPO3 versions. I used a method from another of their utility classes to generate the (absolute) page url https://bitbucket.org/99grad/nnhelpers/src/a21c9811d7b47651b8b08d0247fb176ecb087524/Classes/Utilities/Page.php#lines-201 .
And the crucial point there is the following code I think.

```php
$cObj = \nn\t3::injectClass( \TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::class );
```

The `\nn\t3::injectClass` https://bitbucket.org/99grad/nnhelpers/src/a21c9811d7b47651b8b08d0247fb176ecb087524/Classes/nnhelpers.php#lines-323 method ultimately uses the following:

```php
$objectManager = GeneralUtility::makeInstance(ObjectManager::class);
return $objectManager->get($class);
```

So this is what I meant as inspiration. If I have time in between projects I might try to refactor the code and take inspiration from them with giving credits.

But leaving the extension marked as fully compatible with TYPO3 >= 10 while it isn't, isn't an ideal solution either. So maybe try to adapt based on my suggestions, or wait until I find free time or mention in the docs that this particular function is not compatible for TYPO3 >= 10 or disable it based on `TYPO3_version`.

**Comment by tpinne** [comment]
I found a bit of time to pick the pieces together and created a helper class with no external dependencies. I currently could only test it with TYPO3 10.4.23. But that works. Hope you have the possibility to test it against other versions.

**Comment by tpinne** [comment]
Hi, is there any chance this might get merged?

**Comment by xperseguers** [comment]
Latest version fixes everything in that regards.

**Pull request closed without merging**
